engineStrict: true
ignoreScripts: true
saveExact: true
savePrefix: ''
minimumReleaseAge: 1440
# NOTE: If release age is undefined, verify the dependency manually.
# Once verified, comment out or set to true this line to allow the installation.
minimumReleaseAgeIgnoreMissingTime: false
