/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UnauthenticatedLoginIndexRouteImport } from './routes/_unauthenticated/login/index'
import { Route as AuthenticatedQuestionnairesIndexRouteImport } from './routes/_authenticated/questionnaires/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedQuestionnairesQuestionnaireIdIndexRouteImport } from './routes/_authenticated/questionnaires/$questionnaireId/index'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const UnauthenticatedLoginIndexRoute =
  UnauthenticatedLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionnairesIndexRoute =
  AuthenticatedQuestionnairesIndexRouteImport.update({
    id: '/questionnaires/',
    path: '/questionnaires/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionnairesQuestionnaireIdIndexRoute =
  AuthenticatedQuestionnairesQuestionnaireIdIndexRouteImport.update({
    id: '/questionnaires/$questionnaireId/',
    path: '/questionnaires/$questionnaireId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/questionnaires/': typeof AuthenticatedQuestionnairesIndexRoute
  '/login/': typeof UnauthenticatedLoginIndexRoute
  '/questionnaires/$questionnaireId/': typeof AuthenticatedQuestionnairesQuestionnaireIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesIndexRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/questionnaires/$questionnaireId': typeof AuthenticatedQuestionnairesQuestionnaireIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/questionnaires/': typeof AuthenticatedQuestionnairesIndexRoute
  '/_unauthenticated/login/': typeof UnauthenticatedLoginIndexRoute
  '/_authenticated/questionnaires/$questionnaireId/': typeof AuthenticatedQuestionnairesQuestionnaireIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/questionnaires/'
    | '/login/'
    | '/questionnaires/$questionnaireId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/questionnaires'
    | '/login'
    | '/questionnaires/$questionnaireId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_unauthenticated'
    | '/_public/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/questionnaires/'
    | '/_unauthenticated/login/'
    | '/_authenticated/questionnaires/$questionnaireId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_unauthenticated/login/': {
      id: '/_unauthenticated/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof UnauthenticatedLoginIndexRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/questionnaires/': {
      id: '/_authenticated/questionnaires/'
      path: '/questionnaires'
      fullPath: '/questionnaires/'
      preLoaderRoute: typeof AuthenticatedQuestionnairesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires/$questionnaireId/': {
      id: '/_authenticated/questionnaires/$questionnaireId/'
      path: '/questionnaires/$questionnaireId'
      fullPath: '/questionnaires/$questionnaireId/'
      preLoaderRoute: typeof AuthenticatedQuestionnairesQuestionnaireIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedQuestionnairesIndexRoute: typeof AuthenticatedQuestionnairesIndexRoute
  AuthenticatedQuestionnairesQuestionnaireIdIndexRoute: typeof AuthenticatedQuestionnairesQuestionnaireIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedQuestionnairesIndexRoute: AuthenticatedQuestionnairesIndexRoute,
  AuthenticatedQuestionnairesQuestionnaireIdIndexRoute:
    AuthenticatedQuestionnairesQuestionnaireIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedLoginIndexRoute: typeof UnauthenticatedLoginIndexRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedLoginIndexRoute: UnauthenticatedLoginIndexRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
